### ISSUE TITLE
Requisitos HU 1

### ISSUE THREAD

**Issue by ClauOrtiiz** [ClauOrtiiz/Burger-queen-api-client#5]
- [x]  Recibir code review de al menos una compañera.
- [x]  Hacer test unitarios ,además  testear el producto manualmente (validaciones de inputs).
- [x]  Realizar test de usabilidad e incorporar el feedback del usuario.
- [x]  Desplegar la aplicación y etiquetado de versión (git tag).

**Comment by sofia-torres-v** [comment]
- [x] Debes haber recibido code review de al menos una compañera.
- [x]  Has testeado tu producto manualmente (validaciones de inputs).
- [x]  Hiciste tests de usabilidad e incorporaste el feedback del usuario.
- [x]  Desplegaste tu aplicación y has etiquetado tu versión (git tag).
